service: Logs-pn

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${file(../../commons/credentials.json):stage}
  region: us-east-1
  deploymentBucket:
    name: ${file(../../commons/credentials.json):${self:provider.stage}.deploymentBucket}

  environment:
    STAGE: ${self:provider.stage}
    DB_HOST: ${file(../../commons/credentials.json):${self:provider.stage}.dbHost}
    DB_PORT: ${file(../../commons/credentials.json):${self:provider.stage}.dbPort}
    DB_PASSWORD: ${file(../../commons/credentials.json):${self:provider.stage}.dbPassword}
    DB_USER: ${file(../../commons/credentials.json):${self:provider.stage}.dbUser}
    DB_NAME: ${file(../../commons/credentials.json):${self:provider.stage}.dbName}
    ACCOUNT_ID: ${file(../../commons/credentials.json):${self:provider.stage}.awsAccountId}
    TIGO_USER: ${file(../../commons/credentials.json):${self:provider.stage}.tigoUsername}
    TIGO_PASSWORD: ${file(../../commons/credentials.json):${self:provider.stage}.tigoPassword}
    TIGO_API_KEY: ${file(../../commons/credentials.json):${self:provider.stage}.ApiTipoKey}
    TIGO_SECRET_KEY: ${file(../../commons/credentials.json):${self:provider.stage}.ApiTigoSecret}
    URL_TIGO: ${file(../../commons/credentials.json):${self:provider.stage}.urlTigo}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:Invoke
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - ses:SendEmail
        - SNS:Publish
      Resource: '*'

package:
  include:
    - ../../commons/**
  exclude:
    - node_modules/**

functions:
  createLog:
    handler: handler.create
    timeout: 30
    events:
      - sns:
          topicName: log-${self:provider.stage}-create
          displayName: log-${self:provider.stage}-create
      - http:
          path: createLog
          method: post
          cors:
            origin: '*'
            allowCredentials: true
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          authorizer:
            arn: ${file(../../commons/credentials.json):${self:provider.stage}.pool_arn}
    layers:
      - arn:${file(../../commons/credentials.json):${self:provider.stage}.layer}